image1 = Image( item_id = 1, image_url = "https://i.imgur.com/heaSTsT.jpg")
db.session.add(image1)
image2 = Image( item_id = 1, image_url = "https://i.imgur.com/dzSijA4.jpg")
db.session.add(image2)
image3 = Image( item_id = 1, image_url = "https://i.imgur.com/PhyjY5u.jpg")
db.session.add(image3)
image4 = Image( item_id = 1, image_url = "https://i.imgur.com/hWLKxUz.jpg")
db.session.add(image4)
image5 = Image( item_id = 2, image_url = "https://i.imgur.com/MGoRGKh.jpg")
db.session.add(image5)
image6 = Image( item_id = 2, image_url = "https://i.imgur.com/hLjWbaT.jpg")
db.session.add(image6)
image7 = Image( item_id = 3, image_url = "https://i.imgur.com/1R5AVEb.jpg")
db.session.add(image7)
image8 = Image( item_id = 3, image_url = "https://i.imgur.com/gROdh8L.jpg")
db.session.add(image8)
image9 = Image( item_id = 3, image_url = "https://i.imgur.com/TudFT92.jpg")
db.session.add(image9)
image10 = Image( item_id = 4, image_url = "https://i.imgur.com/qYZfKxp.jpg")
db.session.add(image10)
image11 = Image( item_id = 4, image_url = "https://i.imgur.com/XCIvnoy.jpg")
db.session.add(image11)
image12 = Image( item_id = 5, image_url = "https://i.imgur.com/A8L6ZLL.jpg")
db.session.add(image12)
image13 = Image( item_id = 5, image_url = "https://i.imgur.com/Wk4kQ60.jpg")
db.session.add(image13)
image14 = Image( item_id = 5, image_url = "https://i.imgur.com/Hbu4iqj.jpg")
db.session.add(image14)
image15 = Image( item_id = 5, image_url = "https://i.imgur.com/K0nTO8C.jpg")
db.session.add(image15)
image16 = Image( item_id = 6, image_url = "https://i.imgur.com/q7t4D1J.jpg")
db.session.add(image16)
image17 = Image( item_id = 6, image_url = "https://i.imgur.com/SUCxSEq.jpg")
db.session.add(image17)
image18 = Image( item_id = 7, image_url = "https://i.imgur.com/zni14RR.jpg")
db.session.add(image18)
image19 = Image( item_id = 7, image_url = "https://i.imgur.com/a3vQ9Yh.jpg")
db.session.add(image19)
image20 = Image( item_id = 7, image_url = "https://i.imgur.com/Mahc9Th.jpg")
db.session.add(image20)
image21 = Image( item_id = 8, image_url = "https://i.imgur.com/y8W8kpx.jpg")
db.session.add(image21)
image22 = Image( item_id = 8, image_url = "https://i.imgur.com/siHVqO4.jpg")
db.session.add(image22)
image23 = Image( item_id = 8, image_url = "https://i.imgur.com/my7s7QE.jpg")
db.session.add(image23)
image24 = Image( item_id = 9, image_url = "https://i.imgur.com/2TKXdqt.jpg")
db.session.add(image24)
image25 = Image( item_id = 9, image_url = "https://i.imgur.com/UVLzlAe.jpg")
db.session.add(image25)
image26 = Image( item_id = 9, image_url = "https://i.imgur.com/KdZfeoE.jpg")
db.session.add(image26)
image27 = Image( item_id = 9, image_url = "https://i.imgur.com/Va9dRhp.jpg")
db.session.add(image27)
image28 = Image( item_id = 10, image_url = "https://i.imgur.com/bVu4fiV.jpg")
db.session.add(image28)
image29 = Image( item_id = 10, image_url = "https://i.imgur.com/Pd3IOsi.jpg")
db.session.add(image29)
image30 = Image( item_id = 10, image_url = "https://i.imgur.com/6iJjzhS.jpg")
db.session.add(image30)
image31 = Image( item_id = 10, image_url = "https://i.imgur.com/98c3PDM.jpg")
db.session.add(image31)
image32 = Image( item_id = 10, image_url = "https://i.imgur.com/qy59RI7.jpg")
db.session.add(image32)
image33 = Image( item_id = 11, image_url = "https://i.imgur.com/JTDkYMm.jpg")
db.session.add(image33)
image34 = Image( item_id = 12, image_url = "https://i.imgur.com/1ravpVx.jpg")
db.session.add(image34)
image35 = Image( item_id = 12, image_url = "https://i.imgur.com/iAiqVlb.jpg")
db.session.add(image35)
image36 = Image( item_id = 12, image_url = "https://i.imgur.com/lBk9jdW.jpg")
db.session.add(image36)
image37 = Image( item_id = 13, image_url = "https://i.imgur.com/2733AY5.jpg")
db.session.add(image37)
image38 = Image( item_id = 14, image_url = "https://i.imgur.com/liA6vWS.jpg")
db.session.add(image38)
image39 = Image( item_id = 15, image_url = "https://i.imgur.com/yeIlULn.jpg")
db.session.add(image39)
image40 = Image( item_id = 15, image_url = "https://i.imgur.com/h0S2YZy.jpg")
db.session.add(image40)
image41 = Image( item_id = 15, image_url = "https://i.imgur.com/l2Pum9p.jpg")
db.session.add(image41)
image42 = Image( item_id = 16, image_url = "https://i.imgur.com/6hUwaHQ.jpg")
db.session.add(image42)
image43 = Image( item_id = 16, image_url = "https://i.imgur.com/LQSKuA6.jpg")
db.session.add(image43)
image44 = Image( item_id = 16, image_url = "https://i.imgur.com/h54a6xR.jpg")
db.session.add(image44)
image45 = Image( item_id = 16, image_url = "https://i.imgur.com/S7eyS6P.jpg")
db.session.add(image45)
image46 = Image( item_id = 17, image_url = "https://i.imgur.com/HJvnw0K.jpg")
db.session.add(image46)
image47 = Image( item_id = 18, image_url = "https://i.imgur.com/lTFlD8Z.jpg")
db.session.add(image47)
image48 = Image( item_id = 19, image_url = "https://i.imgur.com/1WmT0lD.jpg")
db.session.add(image48)
image49 = Image( item_id = 19, image_url = "https://i.imgur.com/zKqJbT9.jpg")
db.session.add(image49)
image50 = Image( item_id = 19, image_url = "https://i.imgur.com/T2qDeF8.jpg")
db.session.add(image50)
image51 = Image( item_id = 20, image_url = "https://i.imgur.com/LuhJmYL.jpg")
db.session.add(image51)
image52 = Image( item_id = 21, image_url = "https://i.imgur.com/BXGIZJA.jpg")
db.session.add(image52)
image53 = Image( item_id = 22, image_url = "https://i.imgur.com/F29mA0S.jpg")
db.session.add(image53)
image54 = Image( item_id = 22, image_url = "https://i.imgur.com/7NgjZnr.jpg")
db.session.add(image54)
image55 = Image( item_id = 22, image_url = "https://i.imgur.com/M8dxj02.jpg")
db.session.add(image55)
image56 = Image( item_id = 22, image_url = "https://i.imgur.com/m3wAKz5.jpg")
db.session.add(image56)
image57 = Image( item_id = 23, image_url = "https://i.imgur.com/VZOQLxI.jpg")
db.session.add(image57)
image58 = Image( item_id = 24, image_url = "https://i.imgur.com/patw3NZ.jpg")
db.session.add(image58)
image59 = Image( item_id = 24, image_url = "https://i.imgur.com/SyACKVP.jpg")
db.session.add(image59)
image60 = Image( item_id = 25, image_url = "https://i.imgur.com/qnTTUoY.jpg")
db.session.add(image60)
image61 = Image( item_id = 25, image_url = "https://i.imgur.com/5eRXM8E.jpg")
db.session.add(image61)
image62 = Image( item_id = 25, image_url = "https://i.imgur.com/CLItr7n.jpg")
db.session.add(image62)
image63 = Image( item_id = 25, image_url = "https://i.imgur.com/jMrOecc.jpg")
db.session.add(image63)
image64 = Image( item_id = 25, image_url = "https://i.imgur.com/RbbCHCi.jpg")
db.session.add(image64)
image65 = Image( item_id = 26, image_url = "https://i.imgur.com/nJAprOB.jpg")
db.session.add(image65)
image66 = Image( item_id = 26, image_url = "https://i.imgur.com/TrmAhfJ.jpg")
db.session.add(image66)
image67 = Image( item_id = 26, image_url = "https://i.imgur.com/mllFI0R.jpg")
db.session.add(image67)
image68 = Image( item_id = 26, image_url = "https://i.imgur.com/wchp4vy.jpg")
db.session.add(image68)
