"""changed owner-id and added relationships

Revision ID: 864d4d3a7b1b
Revises: ae2375d726f3
Create Date: 2022-10-16 14:02:31.622688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864d4d3a7b1b'
down_revision = 'ae2375d726f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
